// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtXUN0d-Vp3YEWJgzl3_goQ3NKP3EfSv0',
    appId: '1:864077751623:web:2adbdf0b2556894ac09862',
    messagingSenderId: '864077751623',
    projectId: 'sword-enhance-game',
    authDomain: 'sword-enhance-game.firebaseapp.com',
    storageBucket: 'sword-enhance-game.firebasestorage.app',
    measurementId: 'G-JNFZMLLY47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzI5hlKmd42Psfj3bni2VqcesfKAjnwA',
    appId: '1:864077751623:android:eeb68b9fbf7be23cc09862',
    messagingSenderId: '864077751623',
    projectId: 'sword-enhance-game',
    storageBucket: 'sword-enhance-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZLPMZnHfjPd14p8QmAKdbVLipm5l5to',
    appId: '1:864077751623:ios:46f03428da9fbe70c09862',
    messagingSenderId: '864077751623',
    projectId: 'sword-enhance-game',
    storageBucket: 'sword-enhance-game.firebasestorage.app',
    iosBundleId: 'com.example.swordGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZLPMZnHfjPd14p8QmAKdbVLipm5l5to',
    appId: '1:864077751623:ios:46f03428da9fbe70c09862',
    messagingSenderId: '864077751623',
    projectId: 'sword-enhance-game',
    storageBucket: 'sword-enhance-game.firebasestorage.app',
    iosBundleId: 'com.example.swordGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtXUN0d-Vp3YEWJgzl3_goQ3NKP3EfSv0',
    appId: '1:864077751623:web:4c0e68377687ed59c09862',
    messagingSenderId: '864077751623',
    projectId: 'sword-enhance-game',
    authDomain: 'sword-enhance-game.firebaseapp.com',
    storageBucket: 'sword-enhance-game.firebasestorage.app',
    measurementId: 'G-3DZCKXS61E',
  );
}
